package:
  name: clhep
  version: 2.4.7.2

source:
  url: https://gitlab.cern.ch/CLHEP/CLHEP/-/archive/CLHEP_2_4_7_2/CLHEP-CLHEP_2_4_7_2.tar.gz
  sha256: c40c239fa2c5810b60f4e9ddd6a8cc2ce81b962aa170994748cd2a2b5ac87f84
  folder: CLHEP

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('clhep', max_pin='x.x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
test:
  commands:
    - test -f ${PREFIX}/lib/libCLHEP${SHLIB_EXT}
    - test -d ${PREFIX}/include/CLHEP

about:
  home: http://proj-clhep.web.cern.ch/proj-clhep/
  license: LGPL-3.0-only
  license_file: CLHEP/COPYING.LESSER
  summary: A Class Library for High Energy Physics
  description: |
    It is intended to be a set of HEP specific foundation and utility classes such as
    random generators, physics vectors, geometry and linear algebra.
  doc_url: http://proj-clhep.web.cern.ch/proj-clhep/index.html#docu
  dev_url: https://gitlab.cern.ch/CLHEP/CLHEP

extra:
  recipe-maintainers:
    - giacomov
    - jasercion
    - Areustle
    - chrisburr
    - tkittel
