{% set name = "clhep" %}
{% set version = "2.4.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://proj-clhep.web.cern.ch/proj-clhep/dist1/{{ name }}-{{ version }}.tgz
  sha256: 170161b8e498555f75c6de7936afde956a93fc9aa121a16d779ea602087a3239

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('clhep', max_pin='x.x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libCLHEP${SHLIB_EXT}
    - test -d ${PREFIX}/include/CLHEP

about:
  home: http://proj-clhep.web.cern.ch/proj-clhep/
  license: LGPL-3.0-only
  license_file: CLHEP/COPYING.LESSER
  summary: A Class Library for High Energy Physics
  description: |
    It is intended to be a set of HEP specific foundation and utility classes such as
    random generators, physics vectors, geometry and linear algebra.
  doc_url: http://proj-clhep.web.cern.ch/proj-clhep/index.html#docu
  dev_url: https://gitlab.cern.ch/CLHEP/CLHEP

extra:
  recipe-maintainers:
    - giacomov
    - jasercion
    - Areustle
    - chrisburr
